### ISSUE TITLE
안녕하세요 혹시 grid에 이미지를 삽입 할 수 있을까요?

### ISSUE THREAD

**Issue by bloodiel** [ax5ui/ax5core#2]
안녕하세요 전에 ax:j 를 사용했던 사람인데요 많이 바뀌었네요 ^^

다름 아니라 grid에 이미지를 넣을 수있는 궁금하여 문의 드립니다.

**Comment by thomasJang** [comment]
질문은 https://jsdev.kr/c/axisj/ax5ui 이곳을 이용하세요
